# docs/_config.yml
title: VSaturn Wiki
description: The official wiki and documentation for VSaturn Downloader.
baseurl: "/VSaturn/docs"
url: "https://Mandrusian.github.io"

# Jekyll build settings
markdown: kramdown
permalink: /:title/

# Exclude files/folders from the site build
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor