t# docs/_config.yml
title: VSaturn Wiki
description: The official wiki and documentation for VSaturn Downloader.
baseurl: "/VSaturn/docs" # <--- CHANGED FROM /Mandrusia/docs
url: "https://Mandrusian.github.io"
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
markdown: kramdown
permalink: /:title/
